package com.credit;
dialect  "mvel"

import com.wqh.drools.jbpm.pojo.Users
import com.wqh.drools.jbpm.pojo.Score
import com.wqh.drools.jbpm.pojo.CreditObject
import com.wqh.drools.jbpm.pojo.Credit

rule "creditObject111"
    when
        creditObject:CreditObject(value == "10")
    then
   		System.out.println(creditObject.getUuid()+"========creditObject:CreditObject===========");
        Credit credit = new Credit(creditObject.getUuid(),creditObject.getValue());
        insert(credit);
end


rule "creditObject222"
    when
        creditObject:CreditObject(value == "50")
    then
        Credit credit = new Credit(creditObject.getUuid(),creditObject.getValue());
        insert(credit);
end

rule "creditObject333"
    when
        creditObject:CreditObject(value == "100")
    then
        Credit credit = new Credit(creditObject.getUuid(),creditObject.getValue());
        insert(credit);
end

