package com.rules

import com.wqh.springboot.drools.pojo.Product
import java.math.BigDecimal
import java.util.List
import java.lang.String

global List list


rule Offer4Diamond
    when
        productObject : Product(type == Product.DIAMOND)
    then
        productObject.setDiscount(15);
     end
rule Offer4Gold
    when
        productObject : Product(type == Product.GOLD)
    then
        productObject.setDiscount(25);
     end


rule testNoLoop
    when
        productObject :  Product(discount > 0)
     then
        productObject.setDiscount(productObject.getDiscount() + 1);
        System.out.println(productObject.getDiscount());
        update(productObject)  //默认情况下在规则里面调用update  insert  retract 方法会重新触发规则，可以将 no-loop设置为true
     end

rule test111
    when
        obj : String()
    then
        System.out.println("规则触发"+obj);
end
//rule testInsert
//    salience 1
//    when
//        eval(true)
//    then
//
//     end
//
//rule rule1
//    dialect "java"
//when
//    $bd : BigDecimal()
//    eval($bd.compareTo(BigDecimal.ZERO) > 0)
//then
//    list.add($bd);
// end
