//created on: 2018-12-28
package test2

import com.wqh.drools.jbpm.pojo.Users
import com.wqh.drools.jbpm.pojo.Score
import com.wqh.drools.jbpm.pojo.CreditObject
import com.wqh.drools.jbpm.pojo.Credit


rule "user222"
	ruleflow-group "user"
    when
       $user:Users(name == "wqh222")
    then
        Score score = new Score();
        score.setName($user.getName());
        score.setScore(50);
        insert(score);
end

rule "score222"
	ruleflow-group  "score"
    when
     	score:Score(score==50)
    then
    	CreditObject creditObject = new CreditObject();
    	creditObject.setUuid(score.getName()+"50");
    	creditObject.setValue("50");
    	insert(creditObject);
end



rule "creditObject222"
    ruleflow-group "creditObject"
    when
        creditObject:CreditObject(value == "50")
    then
        Credit credit = new Credit(creditObject.getUuid(),creditObject.getValue());
        insert(credit);
end


