//created on: 2018-12-7
package com.name


import com.wqh.drools.jbpm.pojo.Users
import com.wqh.drools.jbpm.pojo.Score
import com.wqh.drools.jbpm.pojo.Credit
import com.wqh.drools.jbpm.pojo.CreditObject


query "list all credits from working memory"
credit : Credit()
end

rule "user111"
    when
       $user:Users(name == "wqh111")
    then
        System.out.println($user.getName()+"====================");
        Score score = new Score();
        score.setName($user.getName());
        score.setScore(10);
        insert(score);
end

rule "user222"
    when
       $user:Users(name == "wqh222")
    then
        Score score = new Score();
        score.setName($user.getName());
        score.setScore(50);
        insert(score);
end

rule "user333"
     when
        $user:Users(name == "wqh333")
     then
         Score score = new Score();
         score.setName($user.getName());
         score.setScore(100);
         insert(score);
 end
